/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.Banda;
import dao.AvaliaDAO;
import dao.BandaDAO;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gustavo
 */
public class FormAvaliacao extends javax.swing.JInternalFrame {

    private JFrame mdi;
    private Banda bandaSelecionada;

    /**
     * Creates new form FormBanda
     */
    public FormAvaliacao(JFrame mdi) {
        this.mdi = mdi;
        initComponents();
        this.atualizaLista();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BandaNota = new javax.swing.ButtonGroup();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbBandas = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        lnNomebanda = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtBiografia = new javax.swing.JTextArea();
        nota1 = new javax.swing.JRadioButton();
        nota2 = new javax.swing.JRadioButton();
        nota3 = new javax.swing.JRadioButton();
        nota4 = new javax.swing.JRadioButton();
        nota5 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        btAvaliar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JToggleButton();
        jPanel7 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setClosable(true);

        tbBandas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Cod", "Banda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbBandas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBandasMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbBandas);

        lnNomebanda.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lnNomebanda.setText("Banda");

        jScrollPane6.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane6.setEnabled(false);

        txtBiografia.setEditable(false);
        txtBiografia.setBackground(new java.awt.Color(240, 240, 240));
        txtBiografia.setColumns(20);
        txtBiografia.setRows(5);
        txtBiografia.setEnabled(false);
        jScrollPane6.setViewportView(txtBiografia);

        BandaNota.add(nota1);
        nota1.setText("1");
        nota1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nota1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nota1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        BandaNota.add(nota2);
        nota2.setText("2");
        nota2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nota2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nota2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nota2ActionPerformed(evt);
            }
        });

        BandaNota.add(nota3);
        nota3.setText("3");
        nota3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nota3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nota3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nota3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nota3ActionPerformed(evt);
            }
        });

        BandaNota.add(nota4);
        nota4.setText("4");
        nota4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nota4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nota4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        BandaNota.add(nota5);
        nota5.setText("5");
        nota5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nota5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nota5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel4.setText("Sua Avaliação:");

        btAvaliar.setText("Avaliar");
        btAvaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAvaliarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lnNomebanda)
                .addGap(221, 221, 221))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(nota1)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                        .addComponent(btAvaliar))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(nota2)
                        .addGap(18, 18, 18)
                        .addComponent(nota3)
                        .addGap(18, 18, 18)
                        .addComponent(nota4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nota5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(lnNomebanda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                        .addGap(11, 11, 11))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btAvaliar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nota1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nota5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nota4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nota3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nota2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAtualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btAtualizar)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Bandas", jPanel5);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 749, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Indicações", jPanel7);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbBandasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBandasMouseClicked
        if (evt.getClickCount() > 1) {
            JTable obj = (JTable) evt.getComponent();
            int linha = obj.getSelectedRow();
            Integer cod = (Integer) obj.getModel().getValueAt(linha, 0);
            //Banda band;
            bandaSelecionada = new Banda(cod);
            this.preencheTela(bandaSelecionada);
        }
    }//GEN-LAST:event_tbBandasMouseClicked

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        this.atualizaLista();
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAvaliarActionPerformed
        System.out.println(bandaSelecionada.getCod());


        System.out.println(BandaNota.getSelection());


    }//GEN-LAST:event_btAvaliarActionPerformed

    private void nota3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nota3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nota3ActionPerformed

    private void nota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nota2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nota2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BandaNota;
    private javax.swing.JToggleButton btAtualizar;
    private javax.swing.JButton btAvaliar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel lnNomebanda;
    private javax.swing.JRadioButton nota1;
    private javax.swing.JRadioButton nota2;
    private javax.swing.JRadioButton nota3;
    private javax.swing.JRadioButton nota4;
    private javax.swing.JRadioButton nota5;
    private javax.swing.JTable tbBandas;
    private javax.swing.JTextArea txtBiografia;
    // End of variables declaration//GEN-END:variables

    public void atualizaLista() {
        try {
            BandaDAO bandaDAO = new BandaDAO(SistemaBandas.getConexao());
            List<Banda> lista = bandaDAO.listaTodos();
            DefaultTableModel dtm = (DefaultTableModel) this.tbBandas.getModel();
            dtm.setRowCount(0);
            for (Banda banda : lista) {
                dtm.addRow(new Object[]{banda.getCod(), banda.getNome()});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this.mdi, String.format("Erro ao ler as Bandas:%s", ex.getMessage()), "Erro", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(FormAvaliacao.class.getName()).log(Level.WARNING, "Erro ao ler os Departamentos", ex);
        }
    }

    private boolean preencheTela(Banda band) {
        boolean ret = false;
        try {
            BandaDAO bandDAO = new BandaDAO(SistemaBandas.getConexao());
            band = bandDAO.retrieve(band);
            if (band != null && band.getCod() > 0) {
                this.lnNomebanda.setText(band.getNome());
                this.txtBiografia.setText(band.getBiografia());
                ret = true;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this.mdi, String.format("Não foi possível carregar Departamento: %s", ex.getMessage()), "Erro", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(FormAvaliacao.class.getName()).log(Level.SEVERE, null, ex);
        }
        return ret;
    }
}
